### PR TITLE
Update api for Sonarr v4

### LINKED ISSUE #44: Issue communicating with sonarr!
I just noticed this has been looping the attached error for.. however long. I'm assuming it's been since I updated to the new major version of sonarr, on 4.0.0.307 right now in docker. The API key, url and port are all correct but all I see is what's in the picture.

image

### PR DESCRIPTION
**Pull request by Yankees4life**
Updated the api urls for support for v4 as v4 as deprecated the v1 api.

### CODE REVIEW

**Review by whatdaybob — COMMENTED** [review]
@Yankees4life I have submitted changes for v4, I have no way of testing though so can you please do the honours. Under sonarr in config.yml add `version: v4`

**Comment by Yankees4life** [comment]
I tested it out and it runs fine.

**Comment by dotneB** [comment]
I'm getting 
> 2023-01-26 23:26:11,101 - sonarr_youtubedl - DEBUG - Begin call Sonarr to rescan for series_id: 192
> 2023-01-26 23:26:11,101 - sonarr_youtubedl - ERROR -       Failed - Ominous Lectures - Replacement index 1 out of range for positional args tuple

Seems to be comming from these lines from @whatdaybob's commits 0bb9f32ec348769d3f03a4bb8ae1d101f529559f
```
res = self.request_put(
            "{}/{}/command".format(self.base_url),
            None, 
            self.sonarr_api_version,
            data
        )
```
should be 
```
res = self.request_put(
            "{}/{}/command".format(self.base_url, self.sonarr_api_version),
            None,
            data
        )
```

**Comment by whatdaybob** [comment]
I will fix this as soon as I have some free time unless someone can pull request it and I'll be happy to review.

**Pull request closed without merging**
